cmake_minimum_required(VERSION 3.16)
project(mtc_simulation)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(tf2_msgs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(mtc_interfaces REQUIRED)
find_package(gz-sim8 REQUIRED)
find_package(gz-plugin2 REQUIRED COMPONENTS register)
add_library(mtc_simulation_system SHARED src/simulation_system.cpp)
target_link_libraries(mtc_simulation_system gz-sim8::core gz-plugin2::register)
ament_target_dependencies(mtc_simulation_system rclcpp tf2_msgs std_msgs mtc_interfaces)
install(TARGETS mtc_simulation_system LIBRARY DESTINATION lib)
install(DIRECTORY worlds models config DESTINATION share/${PROJECT_NAME})
ament_package()
