const $=id=>document.getElementById(id);let S={},initial=null,selectedVersion=null,selectedNode=null,drawKey='';const names={observe:'读取仿真真值',pregrasp:'到抓取上方',descend:'下降到方块',close:'闭合夹爪',low_lift:'低位抬起',carry:'直接搬运 / 到达放置上方',place:'下降到放置点',release:'打开夹爪',retreat:'向上退出',verify:'独立目标验收',done:'完成',lift_clearance:'新增 · 抬高越障',transfer_clearance:'新增 · 高位横移'};const phases={resetting:'重置中',idle:'等待',executing:'执行中',repairing:'正在改图',success:'验收通过',failure:'执行失败',stopped:'已停止'};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function selected(){return S.versions?.[selectedVersion===null?S.versions.length-1:selectedVersion]}
function draw(){const v=selected(),g=v?.graph||initial;if(!g)return;const status=(v?.index===S.round||!v)?S.node_status:(v?.node_status||{});const key=JSON.stringify([g,status,selectedVersion]);if(key===drawKey)return;drawKey=key;let order=[],current='START',seen=new Set();while(current&&!seen.has(current)){seen.add(current);if(current!=='START')order.push(current);current=g.edges.find(([a,b])=>a===current)?.[1]};let h=order.length*46+12;
$('graph').innerHTML=`<svg width="460" height="${h}" viewBox="0 0 460 ${h}" role="img" aria-label="策略图"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#617e9f"/></marker></defs>${order.map((n,i)=>{let added=!initial.nodes[n];return `${i?`<path d="M230 ${i*46-2} V${i*46+8}" stroke="#617e9f" marker-end="url(#arrow)"/>`:''}<g tabindex="0" class="node ${esc(status?.[n]||'')} ${added?'inserted':''}" data-node="${esc(n)}" transform="translate(44,${i*46+12})"><rect width="372" height="32" rx="9"/><text x="16" y="21">${esc(names[n]||n)}</text><text x="356" y="21" text-anchor="end" style="font-size:10px;fill:#93aac6">${esc(status?.[n]||'')}</text></g>`}).join('')}</svg>`;
document.querySelectorAll('[data-node]').forEach(el=>{el.onclick=()=>{selectedNode=el.dataset.node;detail()};el.onkeydown=e=>{if(e.key==='Enter')el.onclick()}});detail()}
function detail(){const v=selected(),g=v?.graph||initial;if(!g||!selectedNode)return;let events=(S.events||[]).filter(e=>e.node===selectedNode&&e.kind==='skill_output');$('detail-title').textContent=(names[selectedNode]||selectedNode)+' / '+selectedNode;$('detail').textContent=JSON.stringify({definition:g.nodes[selectedNode],last_output:events.at(-1)?.outputs},null,2)}
async function poll(){try{S=await fetch('/api/state').then(r=>r.json());$('phase').textContent=phases[S.phase]||S.phase;$('round').textContent='v'+S.round;$('held').textContent=S.simulation?.world?.attached?'夹持中':'未夹持';$('live').textContent=S.simulation?.fresh?(S.simulation.camera_fresh?'● 仿真与相机在线':'● 仿真在线 · 相机未就绪'):'仿真离线 / 数据过期';$('run').disabled=S.running||!S.simulation?.fresh;$('provider').disabled=S.running;$('reset').disabled=S.running;let opt=$('provider').options[1];opt.disabled=!S.llm_configured;opt.textContent=S.llm_configured?'LLM 修复 · '+S.llm_model:'LLM 修复 · 尚未配置';$('error').textContent=S.error||'';$('runid').textContent=S.run_id||'尚未运行';const w=S.simulation?.world;if(w?.tcp)$('coords').textContent=`TCP [${w.tcp.map(x=>x.toFixed(3)).join(', ')}] · 方块 [${w.cube.map(x=>x.toFixed(3)).join(', ')}] · 仿真 ${w.sim_time.toFixed(1)} s`;
$('versions').innerHTML=(S.versions||[]).map(v=>`<button data-version="${v.index}" class="${v.index===(selectedVersion??S.versions.length-1)?'active':''}">v${v.index} ${v.status==='success'?'✓':v.status==='failure'?'×':'…'}</button>`).join('');document.querySelectorAll('[data-version]').forEach(b=>b.onclick=()=>{selectedVersion=Number(b.dataset.version);drawKey='';draw()});$('patch').textContent=JSON.stringify(selected()?.patch||S.versions?.findLast(v=>v.patch)?.patch||{说明:'初始图尚未修改'},null,2);
const interesting=(S.events||[]).filter(e=>['execution_failed','graph_repaired','verified_success','run_failed','node_start','llm_response'].includes(e.kind));$('events').innerHTML=interesting.slice(-22).reverse().map(e=>`<div class="event ${esc(e.kind)}"><time>${new Date(e.time*1000).toLocaleTimeString()}</time>${esc(e.kind==='node_start'?'执行：'+(names[e.node]||e.node):e.kind==='graph_repaired'?e.patch.reason:e.kind==='verified_success'?'Gazebo 真值验收通过':e.kind==='execution_failed'?'失败节点：'+e.node+' · '+e.error.slice(0,220):e.error||e.kind)}</div>`).join('');document.querySelectorAll('#loop span').forEach(x=>x.classList.toggle('active',x.dataset.p===S.phase));draw();}catch(e){console.error('poll',e);$('live').textContent='控制台连接中断：'+e.message}setTimeout(poll,650)}
$('run').onclick=async()=>{selectedVersion=null;selectedNode=null;const r=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:$('provider').value,max_rounds:3})});if(!r.ok)$('error').textContent=JSON.stringify(await r.json())};$('stop').onclick=()=>fetch('/api/stop',{method:'POST'});$('camera').onload=()=>setTimeout(()=>{$('camera').src='/camera.jpg?t='+Date.now()},180);$('camera').onerror=()=>setTimeout(()=>{$('camera').src='/camera.jpg?t='+Date.now()},1500);fetch('/api/initial-graph').then(r=>r.json()).then(g=>{initial=g;draw()});$('camera').src='/camera.jpg';poll();

$('reset').onclick=async()=>{const r=await fetch('/api/reset',{method:'POST'});if(!r.ok)$('error').textContent=JSON.stringify(await r.json())};
